export const CREATE_REEL_REQUEST = "CREATE_REEL_REQUEST";
export const CREATE_REEL_SUCCESS = "CREATE_REEL_SUCCESS";
export const CREATE_REEL_FAILURE = "CREATE_REEL_FAILURE";
export const DELETE_REEL_REQUEST = "DELETE_REEL_REQUEST";
export const DELETE_REEL_SUCCESS = "DELETE_REEL_SUCCESS";
export const DELETE_REEL_FAILURE = "DELETE_REEL_FAILURE";
export const GET_ALL_REELS_REQUEST = 'GET_ALL_REELS_REQUEST';
export const GET_ALL_REELS_SUCCESS = 'GET_ALL_REELS_SUCCESS';
export const GET_ALL_REELS_FAILURE = 'GET_ALL_REELS_FAILURE';

